### ISSUE TITLE
Fix some minor remaining differences between the official Word template and here

### ISSUE THREAD

**Issue by dhbwmawhd** [whd14d2/vorlage#31]
### TODO

* [x] change thesis type for 2016
* [x] make index
* [x] re-add TOC to TOC
* [x] generate date for signature line (today)
* [x] seperate confidentiality header from block text
* [x] add signature line to confidentiality block with generated date (today)
* [x] choose new online latex compiler (Sharelatex will shut down July 21st)
  * https://github.com/aslushnikov/latex-online
